auth.refreshToken.cookie.timeout=${auth.refreshToken.cookie.timeout}
auth.realm=${auth.realm}
auth.token-endpoint=http://localhost:${auth.port}/realms/${auth.realm}/protocol/openid-connect/token

quarkus.http.access-log.enabled=true

quarkus.http.auth.permission.refimpl1-permission.paths=/restricted
quarkus.http.auth.permission.refimpl1-permission.policy=role-policy-refimpl1
quarkus.http.auth.permission.refimpl1-permission.methods=GET

quarkus.http.auth.policy.role-policy-refimpl1.roles-allowed=${auth.role.provider}

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=Content-Type,Authorization,DPoP
quarkus.http.cors.exposed-headers=DPoP-Nonce
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.port=${backend.port}
quarkus.http.test-port=${backend.port}

quarkus.keycloak.admin-client.server-url=http://localhost:${auth.port}
quarkus.keycloak.admin-client.username=${auth.user}
quarkus.keycloak.admin-client.password=${auth.password}
quarkus.keycloak.devservices.enabled=false
quarkus.keycloak.policy-enforcer.enabled=false

quarkus.oidc.auth-server-url=http://localhost:${auth.port}/realms/${auth.realm}
quarkus.oidc.client-id=${auth.clientId}
quarkus.oidc.credentials.secret=${auth.clientSecret}
quarkus.oidc.token.authorization-scheme=dpop
